// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace WatchesStore.Models;

public partial class Brand
{
    public int BrandId { get; set; }

    public string BrandName { get; set; }

    public string LogoUrl { get; set; }

    public virtual ICollection<Watch> Watches { get; set; } = new List<Watch>();
}