// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace WatchesStore.Models;

public partial class Watch
{
    public int WatchId { get; set; }

    public string Model { get; set; }

    public int BrandId { get; set; }

    public string Description { get; set; }

    public string Specifications { get; set; }

    public decimal Price { get; set; }

    public string ImageUrl { get; set; }

    public bool IsAvailable { get; set; }

    public DateTime CreatedAt { get; set; }

    public virtual Brand Brand { get; set; }
}